# SwiftLintの対象外とする
excluded:
- Pods

# 無効とするルール
disabled_rules:
- multiple_closures_with_trailing_closure # Buttonアクションで発火するので許可
- identifier_name # グローバルのキャラメル大文字定数を許可したい
- cyclomatic_complexity # Translatorで発火するので許可

# デフォで無効とされたルールを有効とする
opt_in_rules:
- conditional_returns_on_newline # 条件式は改行すること

# ルールをカスタム
line_length: 800 # 1行あたりの文字数制限を450に変更
type_name: # Type名が2文字以上なら許可に変更
  min_length: 2
  max_length: 50

