# SwiftLintの対象外とする
excluded:
- Carthage
- Pods

# 無効とするルール
disabled_rules:
- multiple_closures_with_trailing_closure # Buttonアクションで発火するので許可

# デフォで無効とされたルールを有効とする
opt_in_rules:


# ルールをカスタム
line_length: 450 # 1行あたりの文字数制限を450に変更
identifier_name: # 変数名が1文字以上なら許可に変更
  min_length: 1
type_name: # Type名が2文字以上なら許可に変更
  min_length: 2

